services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: carparkdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  carparkapi:
    build:
      context: .
      dockerfile: CarParkFinder.API/Dockerfile
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=carparkdb;Username=postgres;Password=supersecret
    ports:
      - "5000:80"

volumes:
  pgdata:
